### ISSUE TITLE
Button to Toggle Map On and Off

### ISSUE THREAD

**Issue by yaswant2403** [plon/illinispots#1]
Great website! It's super practical and although it's my last year here, I'll definitely be using it a lot.

The 3D Map is great, but on older laptops, it does take up a lot of resources in the browser and makes scrolling and other aspects of the website sluggish. It would be nice to have a button to toggle the map on and off. Similar to this image:

![image](https://github.com/user-attachments/assets/628d92ae-c148-4852-b952-4c289e23dd1c)

Additionally, having an option to just have a 2D Map would be great too.

I can help implement the button for toggling the map if you'd like me to.

**Comment by plon** [comment]
Thanks for the feedback

added map toggle de43f85
